language: r
cache: packages

addons:
  apt:
    packages:
    - libssh-dev
    - libapparmor-dev

matrix:
  include:
    - r: release
      env: R_CODECOV=true
    - r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

r_binary_packages:
  - covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

secure:
  "auH9vehj7OMqodPC1CZ92DsubAzNFi+TxDGVbAlbZQ6w0uwco2PeW/xa0K5a/xsSOGoUtpkU6uD27YxJatIyTez8TNd/r5BXplhrx2rwGlTfgXPG0SWSNYZOAfwiS21CVfwZfGSUD7tfQ+2gpRJKFDqGHVcfkJSxxuGQUfUlhb4="
